import type {Metadata} from "next";
import "../globals.css";
import React from "react";
import {NextIntlClientProvider} from "next-intl";
import {NextSSRPlugin} from "@uploadthing/react/next-ssr-plugin";
import {extractRouterConfig} from "uploadthing/server";
import {ourFileRouter} from "@/app/api/uploadthing/core";
import {getMessages} from "next-intl/server";
import {notFound} from "next/navigation";
import Head from "next/head";

export const metadata: Metadata = {
    title: "E-Commerce",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon.ico',
    },
};

export default async function RootLayout({children, params: {locale}}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    let messages;
    let isRtl = false;
    try {
        messages = await getMessages();
        isRtl = locale === 'fa'
    } catch (error) {
        notFound();
    }

    return (
        <html lang={locale} dir={isRtl ? 'rtl' : 'ltr'}>
        <Head>
            <link rel="icon" href="../../../public/favicon.ico" sizes="any" />
        </Head>
        <body>
        <NextIntlClientProvider messages={messages}>
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}/>
            {children}
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
